/**
 * Phase 13.8 — Room Resource API: /api/workspace/[workspaceId]/rooms/[roomId]
 *
 * Server-only route handler for retrieving and closing collaboration room records.
 *
 * CRITICAL INVARIANTS:
 * - Server-authoritative actor resolution via resolveServerActor.
 * - Server-authoritative timestamps: closed_at is generated by PostgreSQL now(), NEVER from client.
 * - Workspace tenancy and membership enforced on all operations.
 * - Viewers can read (GET), but cannot close rooms (PATCH returns 403).
 * - Row-level locked concurrency serialization via close_collaboration_room_tx.
 * - Recovery: automatically creates/closes room if start was dropped.
 */

import { NextResponse } from "next/server";
import { resolveServerActor } from "../../../../../lib/persistence/server/auth";
import { PersistenceError } from "../../../../../lib/persistence/server/errors";
import { RoomRepository } from "../../../../../lib/persistence/repositories/roomRepository";

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * GET /api/workspace/[workspaceId]/rooms/[roomId]
 * Retrieves single room record by ID.
 */
export async function GET(
  request: Request,
  context: { params: Promise<{ workspaceId: string; roomId: string }> }
) {
  try {
    const { workspaceId, roomId } = await context.params;
    if (!workspaceId || !UUID_REGEX.test(workspaceId)) {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: `Invalid workspace ID format: '${workspaceId}'` } },
        { status: 400 }
      );
    }
    if (!roomId || roomId.trim().length === 0) {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: "roomId cannot be empty" } },
        { status: 400 }
      );
    }

    const actor = await resolveServerActor(request);

    const repository = new RoomRepository();
    const room = await repository.getRoom(actor, workspaceId, roomId.trim());

    return NextResponse.json({ ok: true, room }, { status: 200 });
  } catch (error) {
    if (error instanceof PersistenceError) {
      return NextResponse.json(
        { error: { code: error.code, message: error.message } },
        { status: error.toHttpStatus() }
      );
    }

    const message = error instanceof Error ? error.message : "Failed to retrieve room";
    return NextResponse.json(
      { error: { code: "INTERNAL_ERROR", message } },
      { status: 500 }
    );
  }
}

/**
 * PATCH /api/workspace/[workspaceId]/rooms/[roomId]
 * Terminates collaboration room session in historical record.
 * Body: { status: "closed", lastKnownState?: Record<string, unknown>, title?: string }
 */
export async function PATCH(
  request: Request,
  context: { params: Promise<{ workspaceId: string; roomId: string }> }
) {
  try {
    const { workspaceId, roomId } = await context.params;
    if (!workspaceId || !UUID_REGEX.test(workspaceId)) {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: `Invalid workspace ID format: '${workspaceId}'` } },
        { status: 400 }
      );
    }
    if (!roomId || roomId.trim().length === 0) {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: "roomId cannot be empty" } },
        { status: 400 }
      );
    }

    const actor = await resolveServerActor(request);

    let body: Record<string, unknown> = {};
    try {
      body = await request.json();
    } catch {
      body = {};
    }

    if (body.status !== undefined && body.status !== "closed") {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: `Invalid status transition: '${body.status}'. Only 'closed' is supported.` } },
        { status: 400 }
      );
    }

    const title = typeof body.title === "string" ? body.title.trim() : undefined;
    const lastKnownState = body.lastKnownState && typeof body.lastKnownState === "object"
      ? (body.lastKnownState as Record<string, unknown>)
      : undefined;

    const repository = new RoomRepository();
    const result = await repository.closeRoom(
      actor,
      {
        roomId: roomId.trim(),
        title,
        lastKnownState,
        workspaceId,
      },
      workspaceId
    );

    return NextResponse.json({ ok: true, room: result.room }, { status: 200 });
  } catch (error) {
    if (error instanceof PersistenceError) {
      return NextResponse.json(
        { error: { code: error.code, message: error.message } },
        { status: error.toHttpStatus() }
      );
    }

    const message = error instanceof Error ? error.message : "Failed to close room";
    return NextResponse.json(
      { error: { code: "INTERNAL_ERROR", message } },
      { status: 500 }
    );
  }
}
