/**
 * Phase 13.7 — Meeting Resource API: /api/workspace/[workspaceId]/meetings/[meetingId]
 *
 * Server-only route handler for retrieving and ending meeting records.
 *
 * CRITICAL INVARIANTS:
 * - Server-authoritative actor resolution via resolveServerActor.
 * - Server-authoritative timestamps: ended_at is generated by PostgreSQL now(), NEVER from client.
 * - Workspace tenancy and membership enforced on all operations.
 * - Viewers can read (GET), but cannot end meetings (PATCH returns 403).
 * - Row-level locked concurrency serialization via end_meeting_tx.
 * - Recovery: automatically creates/ends meeting if start was dropped.
 */

import { NextResponse } from "next/server";
import { resolveServerActor } from "../../../../../lib/persistence/server/auth";
import { PersistenceError } from "../../../../../lib/persistence/server/errors";
import { MeetingRepository } from "../../../../../lib/persistence/repositories/meetingRepository";

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * GET /api/workspace/[workspaceId]/meetings/[meetingId]
 * Retrieves single meeting record by ID.
 */
export async function GET(
  request: Request,
  context: { params: Promise<{ workspaceId: string; meetingId: string }> }
) {
  try {
    const { workspaceId, meetingId } = await context.params;
    if (!workspaceId || !UUID_REGEX.test(workspaceId)) {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: `Invalid workspace ID format: '${workspaceId}'` } },
        { status: 400 }
      );
    }
    if (!meetingId || meetingId.trim().length === 0) {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: "meetingId cannot be empty" } },
        { status: 400 }
      );
    }

    const actor = await resolveServerActor(request);

    const repository = new MeetingRepository();
    const meeting = await repository.getMeeting(actor, workspaceId, meetingId.trim());

    return NextResponse.json({ ok: true, meeting }, { status: 200 });
  } catch (error) {
    if (error instanceof PersistenceError) {
      return NextResponse.json(
        { error: { code: error.code, message: error.message } },
        { status: error.toHttpStatus() }
      );
    }

    const message = error instanceof Error ? error.message : "Failed to retrieve meeting";
    return NextResponse.json(
      { error: { code: "INTERNAL_ERROR", message } },
      { status: 500 }
    );
  }
}

/**
 * PATCH /api/workspace/[workspaceId]/meetings/[meetingId]
 * Terminates meeting session in historical record.
 * Body: { status: "ended", title?: string }
 * Note: client-supplied endedAt is strictly ignored; DB sets authoritative now().
 */
export async function PATCH(
  request: Request,
  context: { params: Promise<{ workspaceId: string; meetingId: string }> }
) {
  try {
    const { workspaceId, meetingId } = await context.params;
    if (!workspaceId || !UUID_REGEX.test(workspaceId)) {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: `Invalid workspace ID format: '${workspaceId}'` } },
        { status: 400 }
      );
    }
    if (!meetingId || meetingId.trim().length === 0) {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: "meetingId cannot be empty" } },
        { status: 400 }
      );
    }

    const actor = await resolveServerActor(request);

    let body: Record<string, unknown> = {};
    try {
      body = await request.json();
    } catch {
      body = {};
    }

    if (body.status !== undefined && body.status !== "ended") {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: `Invalid status transition: '${body.status}'. Only 'ended' is supported.` } },
        { status: 400 }
      );
    }

    const title = typeof body.title === "string" ? body.title.trim() : undefined;

    const repository = new MeetingRepository();
    const result = await repository.endMeeting(
      actor,
      {
        meetingId: meetingId.trim(),
        title,
        workspaceId,
      },
      workspaceId
    );

    return NextResponse.json({ ok: true, meeting: result.meeting }, { status: 200 });
  } catch (error) {
    if (error instanceof PersistenceError) {
      return NextResponse.json(
        { error: { code: error.code, message: error.message } },
        { status: error.toHttpStatus() }
      );
    }

    const message = error instanceof Error ? error.message : "Failed to end meeting";
    return NextResponse.json(
      { error: { code: "INTERNAL_ERROR", message } },
      { status: 500 }
    );
  }
}
