/**
 * Phase 13.7 — Meeting Resource API: /api/workspace/[workspaceId]/meetings/[meetingId]
 *
 * Server-only route handler for retrieving and ending meeting records.
 *
 * CRITICAL INVARIANTS:
 * - Server-authoritative actor resolution via resolveServerActor.
 * - Server-authoritative timestamps: ended_at is generated by PostgreSQL now(), NEVER from client.
 * - Workspace tenancy and membership enforced on all operations.
 * - Viewers can read (GET), but cannot end meetings (PATCH returns 403).
 * - Row-level locked concurrency serialization via end_meeting_tx.
 * - Recovery: automatically creates/ends meeting if start was dropped.
 */

import { NextResponse } from "next/server";
import { resolveServerActor } from "../../../../../lib/persistence/server/auth";
import { PersistenceError } from "../../../../../lib/persistence/server/errors";
import { MeetingRepository } from "../../../../../lib/persistence/repositories/meetingRepository";
import type { MeetingInsightType } from "../../../../../lib/persistence/meetingTypes";

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * GET /api/workspace/[workspaceId]/meetings/[meetingId]
 * Retrieves single meeting record by ID.
 */
export async function GET(
  request: Request,
  context: { params: Promise<{ workspaceId: string; meetingId: string }> }
) {
  try {
    const { workspaceId, meetingId } = await context.params;
    if (!workspaceId || !UUID_REGEX.test(workspaceId)) {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: `Invalid workspace ID format: '${workspaceId}'` } },
        { status: 400 }
      );
    }
    if (!meetingId || meetingId.trim().length === 0) {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: "meetingId cannot be empty" } },
        { status: 400 }
      );
    }

    const actor = await resolveServerActor(request);

    const repository = new MeetingRepository();
    const meeting = await repository.getMeeting(actor, workspaceId, meetingId.trim());

    return NextResponse.json({ ok: true, meeting }, { status: 200 });
  } catch (error) {
    if (error instanceof PersistenceError) {
      return NextResponse.json(
        { error: { code: error.code, message: error.message } },
        { status: error.toHttpStatus() }
      );
    }

    const message = error instanceof Error ? error.message : "Failed to retrieve meeting";
    return NextResponse.json(
      { error: { code: "INTERNAL_ERROR", message } },
      { status: 500 }
    );
  }
}

/**
 * PATCH /api/workspace/[workspaceId]/meetings/[meetingId]
 * Terminates meeting session in historical record.
 * Body: { status: "ended", title?: string }
 * Note: client-supplied endedAt is strictly ignored; DB sets authoritative now().
 */
export async function PATCH(
  request: Request,
  context: { params: Promise<{ workspaceId: string; meetingId: string }> }
) {
  try {
    const { workspaceId, meetingId } = await context.params;
    if (!workspaceId || !UUID_REGEX.test(workspaceId)) {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: `Invalid workspace ID format: '${workspaceId}'` } },
        { status: 400 }
      );
    }
    if (!meetingId || meetingId.trim().length === 0) {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: "meetingId cannot be empty" } },
        { status: 400 }
      );
    }

    const actor = await resolveServerActor(request);

    let body: Record<string, unknown> = {};
    try {
      body = await request.json();
    } catch {
      body = {};
    }

    if (body.status !== undefined && body.status !== "ended") {
      return NextResponse.json(
        { error: { code: "VALIDATION_ERROR", message: `Invalid status transition: '${body.status}'. Only 'ended' is supported.` } },
        { status: 400 }
      );
    }

    const title = typeof body.title === "string" ? body.title.trim() : undefined;

    const repository = new MeetingRepository();
    const cleanMeetingId = meetingId.trim();

    const result = await repository.endMeeting(
      actor,
      {
        meetingId: cleanMeetingId,
        title,
        workspaceId,
      },
      workspaceId
    );

    let persistedSegmentsCount = 0;
    if (Array.isArray(body.segments) && body.segments.length > 0) {
      const validatedSegments = body.segments
        .filter((s): s is Record<string, unknown> => Boolean(s && typeof s === "object"))
        .map((s, idx) => ({
          id: typeof s.id === "string" && s.id.trim().length > 0 ? s.id.trim() : `seg-${cleanMeetingId}-${idx}`,
          meetingId: cleanMeetingId,
          speakerId: typeof s.speakerId === "string" && s.speakerId.trim().length > 0 ? s.speakerId.trim() : actor.userId,
          speakerName: typeof s.speakerName === "string" && s.speakerName.trim().length > 0 ? s.speakerName.trim() : "Speaker",
          text: typeof s.text === "string" ? s.text : "",
          timestamp: typeof s.timestamp === "number" ? s.timestamp : Date.now(),
          sequence: typeof s.sequence === "number" ? s.sequence : idx + 1,
          status: "final" as const,
          source: "meeting" as const,
          language: typeof s.language === "string" ? s.language : undefined,
          createdAt: typeof s.createdAt === "string" ? s.createdAt : new Date().toISOString(),
        }))
        .filter((s) => s.text.trim().length > 0);

      if (validatedSegments.length > 0) {
        const segResult = await repository.persistTranscriptSegments(actor, {
          meetingId: cleanMeetingId,
          segments: validatedSegments,
        });
        persistedSegmentsCount = segResult.persistedCount;
      }
    }

    let persistedInsightsCount = 0;
    if (Array.isArray(body.insights) && body.insights.length > 0) {
      const validatedInsights = body.insights
        .filter((ins): ins is Record<string, unknown> => Boolean(ins && typeof ins === "object"))
        .map((ins, idx) => ({
          id: typeof ins.id === "string" && ins.id.trim().length > 0 ? ins.id.trim() : `ins-${cleanMeetingId}-${idx}`,
          meetingId: cleanMeetingId,
          type: (typeof ins.type === "string" ? (ins.type as MeetingInsightType) : "note"),
          title: typeof ins.title === "string" ? ins.title : "Insight",
          summary: typeof ins.summary === "string" ? ins.summary : "",
          sourceSegmentIds: Array.isArray(ins.sourceSegmentIds) ? ins.sourceSegmentIds.map(String) : [],
          speakerIds: Array.isArray(ins.speakerIds) ? ins.speakerIds.map(String) : [],
          timestamp: typeof ins.timestamp === "number" ? ins.timestamp : Date.now(),
          confidence: typeof ins.confidence === "number" ? ins.confidence : undefined,
          createdAt: typeof ins.createdAt === "string" ? ins.createdAt : new Date().toISOString(),
        }));

      if (validatedInsights.length > 0) {
        const insResult = await repository.persistMeetingInsights(actor, {
          meetingId: cleanMeetingId,
          insights: validatedInsights,
        });
        persistedInsightsCount = insResult.persistedCount;
      }
    }

    return NextResponse.json(
      {
        ok: true,
        meeting: result.meeting,
        persistedSegmentsCount,
        persistedInsightsCount,
      },
      { status: 200 }
    );
  } catch (error) {
    if (error instanceof PersistenceError) {
      return NextResponse.json(
        { error: { code: error.code, message: error.message } },
        { status: error.toHttpStatus() }
      );
    }

    const message = error instanceof Error ? error.message : "Failed to end meeting";
    return NextResponse.json(
      { error: { code: "INTERNAL_ERROR", message } },
      { status: 500 }
    );
  }
}
